### ISSUE TITLE
Hi is this possible ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [Bramas/autofill-checker#2]
https://github.com/anttiviljami/browser-autofill-phishing/issues/12

**Comment by Bramas** [comment]
The auto fill mechanism depends on the browser, so we cannot force it to happen when the page loads I think.
 However, a page that wants to steal auto filled information can send it as soon as the auto filled is executed instead of waiting for the form to be submited, that is the reason why my extension is not a good protection.

**Comment by minanagehsalalma** [comment]
Hmmm


> The auto fill mechanism depends on the browser, so we cannot force it to happen when the page loads

Chrome on my pc used to do it once the page loads but now it no longer does .

> a page that wants to steal auto filled information can send it as soon as the auto filled is executed instead of waiting for the form to be submited

There a bit of problems about this 
Like how would it know that's the auto filed not the user typing (so it might send uncompleted values)
